### ISSUE TITLE
Hello, an error occurred while running the code in Generating a grid.

### ISSUE THREAD

**Issue by Ssssz** [bempp/bempp-cl#111]
The code I run is as follows:
```
import bempp.api
grid = bempp.api.shapes.sphere(h=0.1)
```
The error is as follows：
`subprocess.CalledProcessError:` Command 'gmsh.exe -2 C:\Users\lenovo\AppData\Local\Temp\tmp3trsfjcd\tmpbxn5hgb0.geo' returned non-zero exit status 3221225781.`
I have not been able to find the reason for this error.

**Comment by Ssssz** [comment]
Can you tell me the version number of each dependent library？

**Comment by mscroggs** [comment]
Looks like gmsh is causing the error. What version of gmsh are you using? I have 4.4.1 and the snippet you sent works ok.

**Comment by Ssssz** [comment]
> Looks like gmsh is causing the error. What version of gmsh are you using? I have 4.4.1 and the snippet you sent works ok.

I am using version 4.6.0, and the previous problem has been solved. But the following problem appeared again：
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "F:/Users/lenovo/Desktop/工作/code/test_opencl.py", line 7, in <module>
    import bempp.api
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\bempp\api\__init__.py", line 8, in <module>
    import pyopencl as _cl
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\__init__.py", line 28, in <module>
    import pyopencl.cltypes  # noqa: F401
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\cltypes.py", line 22, in <module>
    from pyopencl.tools import get_or_register_dtype
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\tools.py", line 36, in <module>
    from pyopencl._cl import bitlog2  # noqa: F401
ImportError: ImportError: numpy.core.multiarray failed to import
```

**Comment by mscroggs** [comment]
Which version of Pyopencl and numpy are you using? It's working ok for me with pyopencl 2019.1.1 and numpy 1.17.4.

Could you try running `import pyopencl`? It looks like that might fail separate to Bempp.

**Comment by Ssssz** [comment]
> Which version of Pyopencl and numpy are you using? It's working ok for me with pyopencl 2019.1.1 and numpy 1.17.4.
> 
> Could you try running `import pyopencl`? It looks like that might fail separate to Bempp.

I try running  `import pyopencl` and the following error occurred: 
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "F:/Users/lenovo/Desktop/工作/code/test_opencl.py", line 9, in <module>
    import pyopencl
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\__init__.py", line 28, in <module>
    import pyopencl.cltypes  # noqa: F401
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\cltypes.py", line 22, in <module>
    from pyopencl.tools import get_or_register_dtype
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\tools.py", line 36, in <module>
    from pyopencl._cl import bitlog2  # noqa: F401
ImportError: ImportError: numpy.core.multiarray failed to import
```
Can you tell me the version numbers of the following libraries?
`scipy`  `numba` `llvmlite` ` meshio`

**Comment by Ssssz** [comment]
> Which version of Pyopencl and numpy are you using? It's working ok for me with pyopencl 2019.1.1 and numpy 1.17.4.
> 
> Could you try running `import pyopencl`? It looks like that might fail separate to Bempp.
I try running `import pyopencl` and the following error occurred:
 ```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "F:/Users/lenovo/Desktop/test/code/test_opencl.py", line 9, in <module>
    import pyopencl
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\__init__.py", line 28, in <module>
    import pyopencl.cltypes  # noqa: F401
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\cltypes.py", line 22, in <module>
    from pyopencl.tools import get_or_register_dtype
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopencl\tools.py", line 36, in <module>
    from pyopencl._cl import bitlog2  # noqa: F401
ImportError: ImportError: numpy.core.multiarray failed to import
```
Can you tell me the version numbers of the following libraries?
`scipy`  `numba`  `llvmlite`  `meshio`

**Comment by mscroggs** [comment]
It looks like this is caused by an old version of numpy (see eg https://stackoverflow.com/questions/34051737/numpy-core-multiarray-failed-to-import). The replies in that thread suggest updating numpy (or removing and reinstalling numpy) might fix it

**Comment by Ssssz** [comment]
> It looks like this is caused by an old version of numpy (see eg https://stackoverflow.com/questions/34051737/numpy-core-multiarray-failed-to-import). The replies in that thread suggest updating numpy (or removing and reinstalling numpy) might fix it

I still haven't solved this problem, can you tell me the version numbers of scipy, numba and llvmlite you use?
