### ISSUE TITLE
[Bug] fenicsx - Bempp coupling error

### ISSUE THREAD

**Issue by philippweder** [bempp/bempp-cl#212]
The following code from the Helmholtz BEM-FEM coupling tutorial with Fenicsx throws an error:

```
from mpi4py import MPI

from dolfinx.fem import functionspace
from dolfinx.mesh import create_unit_cube
from bempp.api.external import fenicsx

if __name__ == "__main__":
    mesh = create_unit_cube(MPI.COMM_WORLD, 10, 10, 10)

    V = functionspace(mesh, ("CG", 1))
    trace_space, trace_matrix = fenicsx.fenics_to_bempp_trace_data(V)
```

More precisely, it outputs

```
Traceback (most recent call last):
    trace_space, trace_matrix = fenicsx.fenics_to_bempp_trace_data(V)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pydefeat-env/lib/python3.12/site-packages/bempp/api/external/fenicsx.py", line 57, in fenics_to_bempp_trace_data
    family, degree = fenics_space_info(fenics_space)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pydefeat-env/lib/python3.12/site-packages/bempp/api/external/fenicsx.py", line 69, in fenics_space_info
    family = element.family()
             ^^^^^^^^^^^^^^
AttributeError: '_BasixElement' object has no attribute 'family'
```

I think that in the function `fenics_space_info` in the `bempp.api.external.fenicsx` module, it should read
```
def fenics_space_info(fenics_space):
    """Return tuple (family,degree) containing information about a FEniCS space."""
    element = fenics_space.ufl_element()
    family = element.family_name # instead of previously element.family()
    degree = element.degree # instead of previously element.degree()
    return (family, degree)
```

**Comment by mscroggs** [comment]
I think this is fixed in the 0.3.2 release. Please reopen this if not!
